### ISSUE TITLE
`keyboard_ctr` not working with `Waiting for FCU connection`

### ISSUE THREAD

**Issue by bigbellmercy** [HKPolyU-UAV/E2ES#4]
Hello~ Thank you for development!

After I installed it as README.md, I succeeded to launch Gazebo and Rviz. But when I launch `keyboard_ctr.launch`, it shows error message of `Waiting for FCU connection` repeatedly.

In the terminal of `sim.h`, there are some errors as following:
`ERROR: cannot launch node of type [px4/px4]: Cannot locate node of type [px4] in package [px4]. Make sure file exists in package path and permission is set to executable (chmod +x)`

And one more:
`[ WARN] [1616660281.886590426, 595.139000000]: missing <robotNamespace>, set to default: /iris/`

Is there some solution?

**Comment by bigbellmercy** [comment]
I found a solution:

1. Make `px4` folder in `~/catkin_ws/src`.
2. Copy `launch` folder of your px4 project folder such as `~/PX4-Autopilot`, to `~/catkin_ws/src/px4`.

After that the above error disappeared and the `keyboard_ctr` works well.

**Comment by Ttoto** [comment]
Sorry for the late reply and thank you for your feedback. That is the solution, Congrats!

**Comment by bigbellmercy** [comment]
Thanks. And I found another official solution in [px4.io](http://docs.px4.io/master/en/simulation/ros_interface.html) as below:
It seems that the following commands should be run before the last command is run to launch `px4` wrapper.
```
cd <PX4-Autopilot_clone>
DONT_RUN=1 make px4_sitl_default gazebo
source ~/catkin_ws/devel/setup.bash    # (optional)
source Tools/setup_gazebo.bash $(pwd) $(pwd)/build/px4_sitl_default
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$(pwd)
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$(pwd)/Tools/sitl_gazebo
roslaunch px4 posix_sitl.launch
```

**Comment by Boyang--Li** [comment]
Issue solved. Thank you.
