### ISSUE TITLE
KEyboard Control Failing

### ISSUE THREAD

**Issue by natunator** [HKPolyU-UAV/E2ES#5]
When launching keyboard.ctrl file for the simulation, it shows the following warning on the sim.sh launch 👍🏽 
WARN  [PreFlightCheck] Preflight Fail: Accel #0 uncalibrated
WARN  [PreFlightCheck] Preflight Fail: Gyro #0 uncalibrated
WARN  [PreFlightCheck] system power unavailable
The keyboard control launches fine, but the drone doesn't respond.

Also, the simulation isn't showing the cam0 and cam1 images, but showing color images

**Comment by Ttoto** [comment]
Would you please check the PX4 Firmware version?
`cd PX4-Autopilot/
bash ./Tools/setup/ubuntu.sh
git checkout 71db090`
try to clean and rebuild the px4 firmware

**Comment by natunator** [comment]
Yeah, it's the same as 71db090. But it still continued to fail. I cleared out the entire project and built it again from scratch, then it ran fine. I even rebuilt PX4/Firmware directory. Thanks for the help anyways !!
